VM\RecordingSessionBundle\Entity\RecordingSessionUser:
    type: entity
    repositoryClass: VM\RecordingSessionBundle\Repository\RecordingSessionUserRepository
    table: recording_sessions_users
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        email: { type: string, length: 255 }
        firstname: { type: text, nullable: TRUE }
        lastname: { type: text, nullable: TRUE }
        filename: { type: array, nullable: TRUE }
        created_at:
          type: date
          nullable: TRUE
          gedmo:
            timestampable:
              on: create
        updated_at:
          type: datetime
          nullable: TRUE
          gedmo:
            timestampable:
              on: update
        slug:
          type: string
          length: 255
          unique: TRUE
          gedmo:           
             slug:
               separator: -
               fields:
                - firstname
    manyToOne:
      RecordingSession:
        targetEntity: VM\RecordingSessionBundle\Entity\RecordingSession
        inversedBy: RecordingSessionUser
        joinColumns:
          recording_session_id:
            referencedColumnName: id  
    lifecycleCallbacks: {  }