###----- DASHBOARD -----###
mo_dashboard:
    pattern:  /admin
    defaults: { _controller: VMMakerBundle:Collaborator:dashboard }

###----- MAKERS -----###
### MO
mo_maker_show:
    pattern:  /admin/{slug_ent}
    defaults: { _controller: VMMakerBundle:Maker:moShow }

mo_maker_edit:
    pattern:  /admin/{slug_ent}/edit
    defaults: { _controller: VMMakerBundle:Form:makerForm }
    
mo_maker_update:
    pattern:  /admin/{slug_ent}/update
    defaults: { _controller: "VMMakerBundle:Form:makerForm" }

### BO
bo_makers:
    pattern:  /backend/makers
    defaults: { _controller: VMMakerBundle:Maker:boIndex }

bo_maker_new:
    pattern:  /backend/maker/new
    defaults: { _controller: VMMakerBundle:Form:makerForm }

bo_maker_create:
    pattern:  /backend/maker/new
    defaults: { _controller: VMMakerBundle:Form:makerForm }

bo_maker_edit:
    pattern:  /backend/maker/{slug_ent}/edit
    defaults: { _controller: VMMakerBundle:Form:makerForm }

bo_maker_update:
    pattern:  /backend/maker/{slug_ent}/update
    defaults: { _controller: VMMakerBundle:Form:makerForm }

bo_maker_delete:
    pattern:  /backend/maker/{id}/delete
    defaults: { _controller: VMMakerBundle:Form:removeMaker }

bo_maker_show:
    pattern:  /backend/maker/{slug_ent}
    defaults: { _controller: VMMakerBundle:Maker:boShow }

bo_ac_makers:
    pattern:  /backend/autocomplete/maker
    defaults: { _controller: VMMakerBundle:Ajax:makerAutocomplete }

    
bo_ajax_enteprise_update:
    pattern:  /backend/ajax/enteprise/update/{id}/{type}/status/{option}
    defaults: { _controller:VMMakerBundle:Ajax:updateSattus}   
###----- COLLABORATORS -----###

### BACK OFFICE ###
bo_collaborators:
    pattern:  /backend/collaborateurs
    defaults: { _controller: VMMakerBundle:Collaborator:boIndex }

### MIDDLE OFFICE ###
mo_collaborators:
    pattern:  /admin/{slug_ent}/collaborateurs
    defaults: { _controller: VMMakerBundle:Collaborator:moIndex }
    
mo_collaborator_new:
    pattern:  /admin/{slug_ent}/collaborateur/ajout
    defaults: { _controller: VMMakerBundle:Collaborator:collaboratorForm }
    
mo_collaborator_create:
    pattern:  /admin/{slug_ent}/collaborateur/create
    defaults: { _controller: VMMakerBundle:Collaborator:collaboratorForm }
    
mo_collaborator_change_role:
    pattern:  /admin/{slug_ent}/collaborateur/change/roles
    defaults: { _controller: VMMakerBundle:Collaborator:changeRole }

mo_collaborator_remove:
    pattern:  /admin/{slug_ent}/collaborator/{id}/remove
    defaults: { _controller: VMMakerBundle:Collaborator:deleteCollaborator} 
    
##### BO ######    

bo_collaborator_new:
    pattern:   /backend/{slug_ent}/collaborateur/ajout/{for}
    defaults: { _controller: VMMakerBundle:Collaborator:collaboratorForm, for:null }
    requirements:
            for: customer 

bo_collaborator_create:
    pattern:   /backend/{slug_ent}/collaborateur/create/{for}
    defaults: { _controller: VMMakerBundle:Collaborator:collaboratorForm, for:null }
    requirements:
            for: customer    
    
bo_collaborator_show:
    pattern:  /backend/{for}/collaborator/{id}/show
    defaults: { _controller: VMMakerBundle:Collaborator:boShow}

bo_collaborator_remove:
    pattern:  /backend/collaborator/{id}/remove
    defaults: { _controller: VMMakerBundle:Collaborator:deleteCollaborator}  
    
bo_collaborator_change_role:
    pattern:  /backend/collaborateur/change/roles
    defaults: { _controller: VMMakerBundle:Collaborator:changeRole } 

bo_invitation_remove:
    pattern:  /backend/invitation/{id}/remove
    defaults: { _controller: VMMakerBundle:Collaborator:removeInvitation}   

###----- ADVERTS -----###
### MIDDLE OFFICE
mo_adverts:
    pattern:  /admin/{slug_ent}/annonces
    defaults: { _controller: VMMakerBundle:Advert:moIndex }
    
mo_advert_new:
    pattern:  /admin/{slug_ent}/annonce/new/{advert_type}
    defaults: { _controller: VMMakerBundle:Form:moAdvertForm, advert_type: null }
    requirements:
            advert_type: recrutement|formation

mo_advert_show:
    pattern:  /admin/{slug_ent}/annonce/show/{slug_advert}
    defaults: { _controller: VMMakerBundle:Advert:moShow }
    
mo_advert_new:
    pattern:  /admin/{slug_ent}/advert/new/{advert_type}
    defaults: { _controller: VMMakerBundle:Form:advertForm, advert_type: null }
    requirements:
            advert_type: recrutement|formation

mo_advert_create:
    pattern:  /admin/{slug_ent}/advert/create/{advert_type}
    defaults: { _controller: VMMakerBundle:Form:advertForm, advert_type: null }
    requirements:
            advert_type: recrutement|formation

mo_advert_edit:
    pattern:  /admin/{slug_ent}/advert/{slug_advert}/edit/{advert_type}
    defaults: { _controller: VMMakerBundle:Form:advertForm, advert_type: null }
    requirements:
            advert_type: recrutement|formation

mo_advert_update:
    pattern:  /admin/{slug_ent}/advert/{slug_advert}/update/{advert_type}
    defaults: { _controller: VMMakerBundle:Form:advertForm, advert_type: null }
    requirements:
            advert_type: recrutement|formation  

mo_advert_delete:
    pattern:  /admin/{slug_ent}/advert/delete/{slug_advert}/{advert_type}
    defaults: { _controller: VMMakerBundle:Form:removeAdvert }  

### BACK OFFICE
bo_adverts:
    pattern:  /backend/annonces
    defaults: { _controller: VMMakerBundle:Advert:boIndex }

bo_advert_show:
    pattern:  /backend/annonce/{slug_advert}
    defaults: { _controller: VMMakerBundle:Advert:boShow }

bo_advert_new:
    pattern:  /backend/advert/new/{advert_type}
    defaults: { _controller: VMMakerBundle:Form:advertForm, advert_type: null }
    requirements:
            advert_type: recrutement|formation

bo_advert_create:
    pattern:  /backend/advert/create/{advert_type}
    defaults: { _controller: VMMakerBundle:Form:advertForm, advert_type: null }
    requirements:
            advert_type: recrutement|formation

bo_advert_edit:
    pattern:  /backend/advert/{slug_advert}/edit/{advert_type}
    defaults: { _controller: VMMakerBundle:Form:advertForm, advert_type: null }
    requirements:
            advert_type: recrutement|formation

bo_advert_update:
    pattern:  /backend/advert/{slug_advert}/update/{advert_type}
    defaults: { _controller: VMMakerBundle:Form:advertForm, advert_type: null }
    requirements:
            advert_type: recrutement|formation

bo_advert_delete:
    pattern:  /backend/advert/{slug_advert}/delete
    defaults: { _controller: VMMakerBundle:Form:removeAdvert }