parameters:
#    recrut_online_maker.example.class: VM\MakerBundle\Example

services:
#    recrut_online_maker.example:
#        class: %recrut_online_maker.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    collaborator_repository:
        class: VM\MakerBundle\Repository\MakerAdministratorRepository
        arguments: [VMMakerBundle:MakerAdministrator]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    note_repository:
        class: VM\MakerBundle\Repository\MakerNoteRepository
        arguments: [VMMakerBundle:MakerNote]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    maker_invitation_administrator_repository:
        class: VM\MakerBundle\Repository\MakerInvitationAdministratorRepository
        arguments: [VMMakerBundle:MakerInvitationAdministrator]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    maker_repository:
        class: VM\MakerBundle\Repository\Makerepository
        arguments: [VMMakerBundle:Maker]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    advert_repository:
        class: VM\MakerBundle\Repository\AdvertRepository
        arguments: [VMMakerBundle:Advert]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    maker:
        class: VM\MakerBundle\Controller\MakerController