VM\MakerBundle\Entity\Maker:
   properties:
        name:
            - NotBlank: ~
            
VM\MakerBundle\Entity\MakerInvitationAdministrator:
   constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
   properties:
        email:
            - NotBlank: ~
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: true
        roles:
            - NotBlank: ~  
            
VM\MakerBundle\Entity\Advert:
   properties:
        name:
            - NotBlank: ~  
        advert_type:
            - NotBlank: ~    