SO\MovieBundle\Entity\Link:
    type: entity
    table: links
    repositoryClass: SO\MovieBundle\Repository\LinkRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        mixture:
            type: string
            length: '255'
        purevid:
            type: string
            length: '255'
        visible:
            type: boolean
    manyToOne:
      Movie:
        targetEntity: Movie
        inversedBy: Link
        joinColumn:
          name: movie_code
          referencedColumnName: code
    lifecycleCallbacks: {  }
