SO\MovieBundle\Entity\Movie:
    type: entity
    table: movies
    repositoryClass: SO\MovieBundle\Repository\MovieRepository
    fields:
        code:
            type: integer
            id: true
        originalTitle:
            type: string
            length: 255
        title:
            type: string
            length: 255
        poster:
            type: string
            length: 255
            nullable: TRUE
        productionYear:
            type: integer
            nullable: TRUE
        pressRating:
            type: float
            nullable: TRUE
        publicRating:
            type: float
            nullable: TRUE
        keywords:
            type: text
            nullable: TRUE
        synopsis:
            type: text
            nullable: TRUE
        synopsisShort:
            type: text
            nullable: TRUE
        runtime:
            type: integer
            nullable: TRUE
        trailerEmbed:
            type: text
            nullable: TRUE
        slug:
          type: string
          length: 255
          unique: TRUE
          gedmo:
            slug:
              separator: _
              style: camel
              fields:
                - title
    manyToMany:
      Genre:
          targetEntity: Genre
          inversedBy: Movie
          joinTable:
              name: movies_genres
              joinColumns:
                  genre_code:
                      referencedColumnName: code
              inverseJoinColumns:
                  movie_code:
                      referencedColumnName: code
    oneToMany:
      Link:
        targetEntity: Link
        mappedBy: Movie
    lifecycleCallbacks: {  }
