imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@VMUserBundle/Resources/config/services.yml" }

framework:
    #esi:             ~
    #translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation: { enabled: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true
    translator: { fallback: fr }
    default_locale:  "fr"

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    form:
        resources:
            - 'VMGeneralBundle:Default:formDesign.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [VMGeneralBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        lessphp:
            file: %kernel.root_dir%/../vendor/leafo/lessphp/lessc.inc.php
            apply_to: "\.less$"
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
        #yui_js:
            #jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
            #apply_to: "\.js$"
            #file:   %kernel.root_dir%/../vendor/leafo/lessphp/lessc
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        #yui_css:
        #    jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: %kernel.root_dir%/data/data.db3
        # path:     %database_path%

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    port:      587
    username:  %mailer_user%
    password:  %mailer_password%

fp_open_id:
    db_driver: orm
    identity_class: VM\UserBundle\Entity\OpenIdIdentity

fos_facebook:
    alias:  facebook
    app_id: 1417665145123501
    secret: 6f02ce73bb81f03a9ed969558ea2ce8b
    cookie: true
    permissions: [email, user_birthday, user_location] 
    
fos_user:
    db_driver:     orm                        # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                       # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    VM\UserBundle\Entity\User # La classe de l'entité User que nous utilisons`
    group:
        group_class: VM\UserBundle\Entity\Group    
        
stof_doctrine_extensions: 
    default_locale: fr_fr
    translation_fallback: true
    orm: 
        default:
            tree: true
            timestampable: true
            sluggable: true
            translatable: true
            
nelmio_solarium:
    endpoints:
        default:
            dsn: http://localhost:8983/solr/collection1
            timeout: 5
    clients:
        default:
            endpoints: [default]
    
white_october_breadcrumbs: 
    separator: '»'
    viewTemplate: "VMGeneralBundle:Default:breadcrumbs.html.twig"
knp_paginator:
    template:
        pagination: VMGeneralBundle:Default:paginate.html.twig     # sliding pagination control

## ACCESS LISTENER
services:
    recrut.acces.action_listener:
        class: VM\GeneralBundle\Event\MiddleListener
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
        arguments:
            - "@service_container"
            - "@security.context"
    request_listener:
        class: VM\GeneralBundle\Event\RequestListener
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
        arguments:
            - "@service_container"
    recrut_locale.locale_listener:
        class: VM\GeneralBundle\Event\LocaleListener
        arguments: ["%kernel.default_locale%"]
        tags:
            - { name: kernel.event_subscriber }
    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }        

#simple_things_form_extra:
    #help_extension: true