VM\QuestionnaireBundle\Entity\Help:
    type: entity
    table: helps
    repositoryClass: VM\QuestionnaireBundle\Repository\HelpRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        text: { type: text, nullable: TRUE }
    oneToMany:
        Questionnaire:
            targetEntity: VM\QuestionnaireBundle\Entity\Questionnaire
            mappedBy: Help
        Question:
            targetEntity: VM\QuestionnaireBundle\Entity\Question
            mappedBy: Help
        StdQuestionType:
            targetEntity: VM\StandardBundle\Entity\StdQuestionType
            mappedBy: Help
        StdQuestionnaireType:
            targetEntity: VM\StandardBundle\Entity\StdQuestionnaireType
            mappedBy: Help
    lifecycleCallbacks: {  }
