VM\QuestionnaireBundle\Entity\QuestionnaireElement:
    type: entity
    table: questionnaires_elements
    repositoryClass: VM\QuestionnaireBundle\Repository\QuestionnaireElementRepository
    gedmo:
      tree:
        type: nested
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name: { type: string, length: 255 }
        text_description: { type: text, nullable: TRUE }
        position: { type: integer }
        time_limit: { type: integer, nullable: TRUE }
        tag: { type: array, nullable: TRUE }
        display_page: { type: boolean, nullable: TRUE }
        display_next: { type: boolean, nullable: TRUE }
        enclosed_files : { type: text, nullable: TRUE }
        media_type: { type: string, lenght: 50, nullable: TRUE }
        media_allow: { type: boolean, nullable: TRUE }
        lft:
          type: integer
          gedmo:
            - treeLeft
        rgt:
          type: integer
          gedmo:
            - treeRight
        root_id:
          type: integer
          gedmo:
            - treeRoot
        level:
          type: integer
          gedmo:
            - treeLevel
        created_at:
          type: date
          nullable: TRUE
          gedmo:
            timestampable:
              on: create
        updated_at:
          type: datetime
          nullable: TRUE
          gedmo:
            timestampable:
              on: update
        slug:
          type: string
          length: 255
          unique: TRUE
          gedmo:
            slug:
              separator: -
              fields:
                - name
    manyToOne:
      Questionnaire:
        targetEntity: VM\QuestionnaireBundle\Entity\Questionnaire
        inversedBy: QuestionnaireElement
        joinColumns:
          questionnaire_id:
            referencedColumnName: id
      parent:
        targetEntity: VM\QuestionnaireBundle\Entity\QuestionnaireElement
        inversedBy: children
        gedmo:
          - treeParent
        joinColumns:
          parent_id:
            referencedColumnName: id
      StdQuestionnaireTypeElement:
            targetEntity: VM\StandardBundle\Entity\StdQuestionnaireTypeElement
            inversedBy: QuestionnaireElement
            joinColumns:
                std_questionnaire_type_element_id:
                  referencedColumnName: id
    oneToMany:
         children:
            targetEntity: VM\QuestionnaireBundle\Entity\QuestionnaireElement
            mappedBy: parent
         QuestionnaireElementPayment:
            targetEntity: VM\QuestionnaireBundle\Entity\QuestionnaireElementPayment
            mappedBy: QuestionnaireElement
    oneToOne:
         Question:
          targetEntity:  VM\QuestionnaireBundle\Entity\Question
          mappedBy: QuestionnaireElement
          cascade: ["persist", "merge"]   
    lifecycleCallbacks: {  }
