VM\QuestionnaireBundle\Entity\QuestionnaireQuestionChoice:
    type: entity
    table: questionnaires_questions_choices
    repositoryClass: VM\QuestionnaireBundle\Repository\QuestionnaireQuestionChoiceRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name: { type: string, lenght: 255, nullable: TRUE }
        position: { type: integer }
        ranking : { type: integer, nullable: TRUE }
        good_response: { type: boolean, nullable: TRUE }
        created_at:
          type: date
          nullable: TRUE
          gedmo:
            timestampable:
              on: create
        updated_at:
          type: datetime
          nullable: TRUE
          gedmo:
            timestampable:
              on: update
    oneToMany:
      QuestionnaireQuestionResponse:
        targetEntity: VM\QuestionnaireBundle\Entity\QuestionnaireQuestionResponse
        mappedBy: QuestionnaireQuestionChoice
      children:
        targetEntity: VM\QuestionnaireBundle\Entity\QuestionnaireQuestionChoice
        mappedBy: NextQuestion  
    manyToOne:
      NextQuestion:
        targetEntity: VM\QuestionnaireBundle\Entity\QuestionnaireQuestionChoice
        inversedBy: children
        joinColumns:
          next_question_id:
            referencedColumnName: id
      Question:
        targetEntity: VM\QuestionnaireBundle\Entity\Question
        inversedBy: QuestionnaireQuestionChoice
        joinColumns:
          question_id:
            referencedColumnName: id
      
    lifecycleCallbacks: {  }
