### Backend Questionnaire ###    
bo_questionnaires:
    pattern:  /backend/questionnaires
    defaults: { _controller: VMQuestionnaireBundle:Questionnaire:boIndex }

bo_questionnaire_new:
    pattern:  /backend/questionnaire/new
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireForm } 

bo_questionnaire_create:
    pattern:  /backend/questionnaire/create
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireForm }
    
bo_enterprise_questionnaire_new:
    pattern:  /backend/{slug_ent}/questionnaire/new
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireForm } 
    
bo_enterprise_questionnaire_create:
    pattern:  /backend/{slug_ent}/questionnaire/create
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireForm } 
bo_questionnaire_edit:
    pattern:  /backend/questionnaire/edit/{slug_quest}
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireForm }   
    
bo_questionnaire_update:
    pattern:  /backend/questionnaire/update/{slug_quest}
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireForm } 
    
bo_questionnaire_show:
    pattern:  /backend/questionnaire/{slug_quest}
    defaults: { _controller: VMQuestionnaireBundle:Questionnaire:boShow } 

bo_questionnaire_duplicate:
    pattern:  /backend/questionnaire/{slug_quest}/duplicate/{actionType}
    defaults: { _controller: VMQuestionnaireBundle:Duplicate:questionnaireDuplicate, actionType:duplicate }
bo_questionnaire_duplicate_create:
   pattern:  /backend/questionnaire/{slug_quest}/duplicate/{actionType}
   defaults: { _controller: VMQuestionnaireBundle:Duplicate:questionnaireDuplicate, actionType:duplicate }
    
bo_questionnaire_change_status:
    pattern:  /backend/questionnaire/{slug_quest}/change/{status}/status
    defaults: { _controller: VMQuestionnaireBundle:Form:boChangeQuestionnaireStatus, status:null }
    requirements:
            status: approuve|disapprouve|publish|depublish
bo_questionnaire_invitation:
    pattern:  /backend/questionnaire/{slug_quest}/invitation
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireInvitation} 
    
bo_questionnaire_user_remove_all:
    pattern:  /backend/repondant/{slug_quest}/remove/all
    defaults: { _controller: VMQuestionnaireBundle:Form:removeQuestionnaireUserAll }           
            
### Backend Questionnaire element ###    
bo_questionnaire_elements:
    pattern:  /backend/questionnaire/{slug_quest}/elements
    defaults: { _controller: VMQuestionnaireBundle:Element:boShow }

bo_questionnaire_element_new:
    pattern:  /backend/questionnaire/{slug_quest}/element/new
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireElementForm }
    
bo_questionnaire_element_create:
    pattern:  /backend/questionnaire/{slug_quest}/element/create
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireElementForm }
       
bo_questionnaire_element_edit:
    pattern:  /backend/questionnaire/{slug_quest}/element/edit/{id}
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireElementForm } 
    
bo_element_duplicate:
    pattern:  /backend/questionnaire/{slug_quest}/question/duplicate/{type}/{id}
    defaults: { _controller: VMQuestionnaireBundle:Duplicate:elementDuplicate }  
    
bo_questionnaire_element_update:
    pattern:  /backend/questionnaire/{slug_quest}/element/update/{id}
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireElementForm }
    
bo_questionnaire_element_update_ajax:
    pattern:  /backend/questionnaire/{slug_quest}/element/update/ajax/{id}
    defaults: { _controller: VMQuestionnaireBundle:Element:questionnaireElementAjaxSave }     
bo_questionnaire_element_delete:
    pattern:  /backend/questionnaire/{slug_quest}/element/delete/{id}
    defaults: { _controller: VMQuestionnaireBundle:Element:questionnaireElementRemove }  

bo_questionnaire_element_config_form:
    pattern:  /backend/questionnaire/{slug_quest}/element/{id}/form/config
    defaults: { _controller: VMQuestionnaireBundle:Element:questionnaireElementConfigForm }     
    
### Backend Questionnaire Respondant Users ###    
bo_questionnaire_users:
    pattern:  /backend/repondants
    defaults: { _controller: VMQuestionnaireBundle:Questionnaire:boQuestionnaireRespondantIndex }
    
bo_questionnaire_user_remove:
    pattern:  /backend/repondant/{repondant_id}/remove
    defaults: { _controller: VMQuestionnaireBundle:Element:removeQuestionnaireUser }
bo_questionnaire_user_respondants:
    pattern:  /backend/questionnaire/{slug_quest}/repondants
    defaults: { _controller: VMQuestionnaireBundle:Questionnaire:boQuestionnaireRespondantIndex }
    
bo_questionnaire_user_respondant_show:
    pattern:  /backend/questionnaire/{slug_quest}/repondant/{respondant_id}
    defaults: { _controller: VMQuestionnaireBundle:Questionnaire:boRespondantShow }

    
bo_questionnaire_user_response_rankin_ajax:
    pattern:  /backend/questionnaire/{slug_quest}/response/rankin/ajax/{repondant_id}/{question_id}
    defaults: { _controller: VMQuestionnaireBundle:Element:questionnaireResponseAjaxSave } 
    
bo_questionnaire_user_response_total_note_ajax:
    pattern:  /backend/questionnaire/{slug_quest}/response/total_note/ajax/{repondant_id}
    defaults: { _controller: VMQuestionnaireBundle:Element:questionnaireResponseTotalNoteAjaxSave }
    
bo_questionnaire_question_response_download:
   pattern:  /backend/questionnaire/{slug_quest}/response/download/{response_id}
   defaults: { _controller: VMQuestionnaireBundle:QuestionnaireUser:boQuestionnaireResponseDownload }
   
bo_questionnaire_user_respondant_decisions:
    pattern:  backend/questionnaire/{slug_quest}/repondant/{questionnaire_user_id}/decision
    defaults: { _controller: VMQuestionnaireBundle:Questionnaire:boQuestionnaireRespondantDecisionIndex }    
    
bo_questionnaire_user_respondant_change_status:
    pattern:  backend/questionnaire/{slug_quest}/repondant/{questionnaire_user_id}/statut/{status}
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireRespondantChangeStatus }    

bo_questionnaire_preview_show:
    pattern: /backend/questionnaire/{slug_quest}/preview/show
    defaults: { _controller: VMQuestionnaireBundle:QuestionnaireUser:boQuestionnairePreviewShow }

bo_questionnaire_process:
   pattern:  /backend/questionnaire/{slug_quest}/preview/reponse
   defaults: { _controller: VMQuestionnaireBundle:QuestionnaireUser:boQuestionnaireProcess }
   
bo_questionnaire_success:
   pattern:  /backend/questionnaire/{slug_quest}/preview/success
   defaults: { _controller: VMQuestionnaireBundle:QuestionnaireUser:boQuestionnaireSuccess }    
bo_questionnaire_element_reposition:
    pattern:  /backend/questionnaire/{slug_quest}/element/reposition
    defaults: { _controller: VMQuestionnaireBundle:Element:questionnaireElementReposition }   
    
### Admin Side Questionnaire ###   
mo_questionnaires:
    pattern:  /admin/{slug_ent}/questionnaires
    defaults: { _controller: VMQuestionnaireBundle:Questionnaire:moIndex }

mo_questionnaire_creation:
    pattern:  /admin/{slug_ent}/questionnaire/creation
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireCreation }

mo_questionnaire_models:
    pattern:  /admin/{slug_ent}/questionnaire-models
    defaults: { _controller: VMQuestionnaireBundle:QuestionnaireModel:index }

mo_questionnaire_new:
    pattern:  /admin/{slug_ent}/questionnaire/new
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireForm }
    
mo_questionnaire_create:
    pattern:  /admin/{slug_ent}/questionnaire/create
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireForm }
    
mo_questionnaire_edit:
    pattern:  /admin/{slug_ent}/questionnaire/edit/{slug_quest}
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireForm }   
    
mo_questionnaire_update:
    pattern:  /admin/{slug_ent}/questionnaire/update/{slug_quest}
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireForm } 
    
mo_questionnaire_show:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}
    defaults: { _controller: VMQuestionnaireBundle:Questionnaire:moShow }
    
mo_questionnaire_duplicate:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/duplicate
    defaults: { _controller: VMQuestionnaireBundle:Duplicate:questionnaireDuplicate, actionType:duplicate }
    
mo_questionnaire_invitation:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/invitation
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireInvitation }

mo_questionnaire_status:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/status/{status}
    defaults: { _controller: VMQuestionnaireBundle:Questionnaire:status }
mo_questionnaire_preview_show:
    pattern: /admin/{slug_ent}/questionnaire/{slug_quest}/preview/show
    defaults: { _controller: VMQuestionnaireBundle:QuestionnaireUser:moQuestionnairePreviewShow }

mo_questionnaire_process:
   pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/preview/reponse
   defaults: { _controller: VMQuestionnaireBundle:QuestionnaireUser:moQuestionnaireProcess }
mo_questionnaire_success:
   pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/preview/success
   defaults: { _controller: VMQuestionnaireBundle:QuestionnaireUser:moQuestionnaireSuccess }

## LIST COMPONENT QUESTIONNAIRE
mo_questionnaires_list:
   pattern:  /admin/{slug_ent}/questionnaires/list
   defaults: { _controller: VMQuestionnaireBundle:Questionnaire:questionnaireList }
bo_questionnaires_list:
   pattern:  /backend/questionnaires/list
   defaults: { _controller: VMQuestionnaireBundle:Questionnaire:questionnaireList }
   
### Middle  Side User respondants ###    
mo_questionnaire_user_respondants:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/repondants
    defaults: { _controller: VMQuestionnaireBundle:Questionnaire:moQuestionnaireRespondantIndex }
    
mo_questionnaire_user_respondant_show:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/repondant/{respondant_id}
    defaults: { _controller: VMQuestionnaireBundle:Questionnaire:moRespondantShow }
    
mo_questionnaire_user_respondant_decisions:
    pattern:  admin/{slug_ent}/questionnaire/{slug_quest}/repondant/{questionnaire_user_id}/decision
    defaults: { _controller: VMQuestionnaireBundle:Questionnaire:moQuestionnaireRespondantDecisionIndex }
    
mo_questionnaire_user_respondant_change_status:
    pattern:  admin/{slug_ent}/questionnaire/{slug_quest}/repondant/{questionnaire_user_id}/statut/{status}
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireRespondantChangeStatus }
    
mo_questionnaire_user_response_rankin_ajax:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/response/rankin/ajax/{repondant_id}/{question_id}
    defaults: { _controller: VMQuestionnaireBundle:Element:questionnaireResponseAjaxSave } 
    
mo_questionnaire_user_response_total_note_ajax:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/response/total_note/ajax/{repondant_id}
    defaults: { _controller: VMQuestionnaireBundle:Element:questionnaireResponseTotalNoteAjaxSave }

mo_questionnaire_users_list:
    pattern:  /admin/{slug_ent}/repondants/list
    defaults: { _controller: VMQuestionnaireBundle:QuestionnaireUser:moRespondantsList }
    
    
###Element section Middle Office ###
##Question section##
mo_questionnaire_question_new:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/question/new
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireQuestionForm }
mo_element_duplicate:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/question/duplicate/{type}/{id}
    defaults: { _controller: VMQuestionnaireBundle:Duplicate:elementDuplicate }
    
mo_questionnaire_elements:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/elements
    defaults: { _controller: VMQuestionnaireBundle:Element:moShow }
    
mo_questionnaire_elements_video:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/elements/video
    defaults: { _controller: VMQuestionnaireBundle:Element:video }
    
mo_questionnaire_element_config_form:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/element/{id}/form/config
    defaults: { _controller: VMQuestionnaireBundle:Element:questionnaireElementConfigForm }

mo_questionnaire_element_new:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/element/new
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireElementForm }
    
mo_questionnaire_element_create:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/element/create
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireElementForm }
       
mo_questionnaire_element_edit:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/element/edit/{id}
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireElementForm }   
mo_questionnaire_element_update:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/element/update/{id}
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireElementForm }
    
mo_questionnaire_element_update_ajax:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/element/update/ajax/{id}
    defaults: { _controller: VMQuestionnaireBundle:Element:questionnaireElementAjaxSave }  
    
mo_questionnaire_element_child_new:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/element/{parent_id}/new
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireElementForm }
    
mo_questionnaire_element_child_create:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/element/{parent_id}/create
    defaults: { _controller: VMQuestionnaireBundle:Form:questionnaireElementForm }

mo_questionnaire_element_reposition:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/element/reposition
    defaults: { _controller: VMQuestionnaireBundle:Element:questionnaireElementReposition }    
mo_questionnaire_element_delete:
    pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/element/delete/{id}
    defaults: { _controller: VMQuestionnaireBundle:Element:questionnaireElementRemove }  

mo_questionnaire_question_response_download:
   pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/response/download/{response_id}
   defaults: { _controller: VMQuestionnaireBundle:QuestionnaireUser:moQuestionnaireResponseDownload }

mo_questionnaire_element_media_upload:
   pattern:  /admin/{slug_ent}/questionnaire/{slug_quest}/mediaUpload
   defaults: { _controller: VMQuestionnaireBundle:Form:elementMediaUpload }
   
###User questionnaire###    
fo_questionnaire_show:
   pattern:  /questionnaire/{slug_quest}
   defaults: { _controller: VMQuestionnaireBundle:QuestionnaireUser:foQuestionnaireShow }

fo_questionnaire_show_locale:
   pattern:  /{_locale}/questionnaire/{slug_quest}
   defaults: { _controller: VMQuestionnaireBundle:QuestionnaireUser:foQuestionnaireShow, _locale: en }
   requirements:
       _locale: en|fr

fo_questionnaire_login_create:
   pattern:  /questionnaire/{slug_quest}/login
   defaults: { _controller: VMQuestionnaireBundle:QuestionnaireUser:foQuestionnaireLogin }

fo_question_get_name:
   pattern:  /questionnaire/{slug_quest}/question/{id}
   defaults: { _controller: VMQuestionnaireBundle:Video:foGetQuestionName}
   
fo_questionnaire_save_video:
   pattern:  /questionnaire/{slug_quest}/reponse/save
   defaults: { _controller: VMQuestionnaireBundle:Video:foSave}
   
fo_questionnaire_process:
   pattern:  /questionnaire/{slug_quest}/reponse
   defaults: { _controller: VMQuestionnaireBundle:QuestionnaireUser:foQuestionnaireProcess}

fo_questionnaire_success:
   pattern:  /questionnaire/{slug_quest}/success
   defaults: { _controller: VMQuestionnaireBundle:QuestionnaireUser:foQuestionnaireSuccess }

####### StdQuestionnaireTypeElement    ######
####### Bakend   ######

bo_helps:
    pattern:  /backend/helps
    defaults: { _controller: "VMQuestionnaireBundle:Help:boIndex" }
    
bo_help_new:
    pattern:  /backend/help/new
    defaults: { _controller: "VMQuestionnaireBundle:Help:helpForm" } 
   
bo_help_edit:
    pattern:  /backend/help/{id}/edit
    defaults: { _controller: "VMQuestionnaireBundle:Help:helpForm" }
    
bo_help_create:
    pattern:  /backend/help/create
    defaults: { _controller: "VMQuestionnaireBundle:Help:helpForm" }    
    requirements: { _method: post }
    
bo_help_update:
    pattern:  /backend/help/{id}/update
    defaults: { _controller: "VMQuestionnaireBundle:Help:helpForm" }
    requirements: { _method: post }
    
bo_help_show:
    pattern:  /backend/help/{id}/show
    defaults: { _controller: "VMQuestionnaireBundle:Help:boShow"}
    
bo_help_delete:
    pattern:  /backend/help/{id}/remove
    defaults: { _controller: "VMQuestionnaireBundle:Help:boDelete"}
