parameters:
#    recrut_online_questionnaire.example.class: VM\QuestionnaireBundle\Example

services:
#    recrut_online_questionnaire.example:
#        class: %recrut_online_questionnaire.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

     questionnaire_repository:
        class: VM\QuestionnaireBundle\Repository\QuestionnaireRepository
        arguments: [VMQuestionnaireBundle:Questionnaire]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
     questionnaire_element_repository:
        class: VM\QuestionnaireBundle\Repository\QuestionnaireElementRepository
        arguments: [VMQuestionnaireBundle:QuestionnaireElement]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
     questionnaire_user_repository:
        class: VM\QuestionnaireBundle\Repository\QuestionnaireUserRepository
        arguments: [VMQuestionnaireBundle:QuestionnaireUser]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
     question_repository:
        class: VM\QuestionnaireBundle\Repository\QuestionRepository
        arguments: [VMQuestionnaireBundle:Question]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
     help_repository:
        class: VM\QuestionnaireBundle\Repository\HelpRepository
        arguments: [VMQuestionnaireBundle:Help]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository    
     question:
        class:        FormaSearch\QuestionnaireBundle\Form\QuestionType
        arguments:    [doctrine]   
     questionnaire_question_choice_repository:
        class: VM\QuestionnaireBundle\Repository\QuestionnaireQuestionChoiceRepository
        arguments: [VMQuestionnaireBundle:QuestionnaireQuestionChoice]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
     questionnaire_question_response_repository:
        class: VM\QuestionnaireBundle\Repository\QuestionnaireQuestionResponseRepository
        arguments: [VMQuestionnaireBundle:QuestionnaireQuestionResponse]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository   
     
     duplicate_controller:
        class:        VM\QuestionnaireBundle\Controller\DuplicateController
        arguments:
            - "@service_container"   