VM\QuestionnaireBundle\Entity\Questionnaire:
    properties:
       name:
            - NotBlank: { message: Nom obligatoire }
       text_introduction:
            - NotBlank: { message: Introduction can not be blank } 
       StdQuestionnaireType:
            - NotBlank: { message: Vous devez choisir un type de questionnaire }
       text_presentation:
            - NotBlank: { message: Presentation can not be blank } 
       mail_invitation:
            - NotBlank: { message: Mail invitation content can not be blank }
       mail_accepted:
            - NotBlank: { message: Mail accepted content can not be blank } 
       mail_refused:
            - NotBlank: { message: Mail refused content can not be blank } 

VM\QuestionnaireBundle\Entity\QuestionnaireElement:
    properties:
       name:
           - NotBlank: { message: Name can not be blank } 
       StdQuestionnaireTypeElement:
           - NotBlank: { message: Select type du questionnaire element }

VM\QuestionnaireBundle\Entity\Help:
    properties:
       text:
           - NotBlank: { message: Name can not be blank }
VM\QuestionnaireBundle\Entity\Question:
    properties:  
        
VM\QuestionnaireBundle\Entity\QuestionnaireUser:
   properties:
        
        email:
            - NotBlank: ~
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: true
        phone_number:
             - NotBlank: ~
             - Regex:
                  pattern: "/\d/"
                  message: Your phone number should contain numbers only
             - Length:
                  min: 6
                  max: 20
                  exactMessage:  Phone number should have less than 20 digits
                 
                 
               