parameters:
#    recrut_online_standard.example.class: FP\StandardBundle\Example

services:
    std_questionnaire_type_element_repository:
        class: FP\StandardBundle\Repository\StdQuestionnaireTypeElementRepository
        arguments: [FPStandardBundle:StdQuestionnaireTypeElement]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    std_question_type_repository:
        class: FP\StandardBundle\Repository\StdQuestionTypeRepository
        arguments: [FPStandardBundle:StdQuestionType]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    std_category_repository:
        class: FP\StandardBundle\Repository\StdCategoryRepository
        arguments: [FPStandardBundle:StdCategory]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    std_question_type_repository:
        class: FP\StandardBundle\Repository\StdQuestionTypeRepository
        arguments: [FPStandardBundle:StdQuestionType]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    std_questionnaire_type_repository:
        class: FP\StandardBundle\Repository\StdQuestionnaireRepository
        arguments: [FPStandardBundle:StdQuestionnaireType]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    std_questionnaire_type_element_repository:
        class: FP\StandardBundle\Repository\StdQuestionnaireTypeElementRepository
        arguments: [FPStandardBundle:StdQuestionnaireTypeElement]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
