so_movie_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SOMovieBundle:Default:index }
    
so_movie_show:
    pattern:  /movie/{code}
    defaults: { _controller: SOMovieBundle:Movie:show }
