so_movie_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: SOMovieBundle:Default:index }
    
so_movie_show:
    pattern:  /movie/{slug}
    defaults: { _controller: SOMovieBundle:Movie:show }
    
so_movie_list:
    pattern:  /movie/list/
    defaults: { _controller: SOMovieBundle:Movie:list }

so_movie_video:
    pattern:  /movie/video/{slug}/{type}/{movieCode}
    defaults: { _controller: SOMovieBundle:Movie:video, type: "n", movieCode: NULL }