parameters:
    so_movie.controller.class: SO\MovieBundle\Controller\MovieController

services:
   so_movie.controller:
        class: %so_movie.controller.class%
        arguments: [@service_container]
        calls:
            - [ setContainer, [@service_container] ]
   movie_repository:
        class: SO\MovieBundle\Repository\MovieRepository
        arguments: [SOMovieBundle:Movie]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
