parameters:
#    poker_standard.example.class: Poker\StandardBundle\Example

services:
    std_questionnaire_type_element_repository:
        class: Poker\StandardBundle\Repository\StdQuestionnaireTypeElementRepository
        arguments: [PokerStandardBundle:StdQuestionnaireTypeElement]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    std_question_type_repository:
        class: Poker\StandardBundle\Repository\StdQuestionTypeRepository
        arguments: [PokerStandardBundle:StdQuestionType]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    std_category_repository:
        class: Poker\StandardBundle\Repository\StdCategoryRepository
        arguments: [PokerStandardBundle:StdCategory]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    std_question_type_repository:
        class: Poker\StandardBundle\Repository\StdQuestionTypeRepository
        arguments: [PokerStandardBundle:StdQuestionType]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    std_questionnaire_type_repository:
        class: Poker\StandardBundle\Repository\StdQuestionnaireRepository
        arguments: [PokerStandardBundle:StdQuestionnaireType]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    std_questionnaire_type_element_repository:
        class: Poker\StandardBundle\Repository\StdQuestionnaireTypeElementRepository
        arguments: [PokerStandardBundle:StdQuestionnaireTypeElement]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
