FP\MailerBundle\Entity\Mailer:
    properties:
       name:
            - NotBlank: { message: Name can not be blank } 
       subject:
            - NotBlank: { message: Subject can not be blank } 
       template:
            - NotBlank: { message: Template can not be blank } 
       description:
            - NotBlank: { message: Description can not be blank }

FP\MailerBundle\Entity\MailerCategory:
    properties:
       name:
            - NotBlank: { message: Name can not be blank }             
