vm_video_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: VMVideoBundle:Default:index }

mo_dashboard:
    pattern:  /admin/videos
    defaults: { _controller: VMVideoBundle:Default:index }
    
fo_make_link:
    pattern:  /video/transform
    defaults: { _controller: VMVideoBundle:Default:makeLink }