parameters:
#    recrut_online_feedback.example.class: VM\FeedbackBundle\Example

services:
#    recrut_online_feedback.example:
#        class: %recrut_online_feedback.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
        
        feedback_repository:
          class:  VM\FeedbackBundle\Repository\FeedbackRepository
          arguments: [VMFeedbackBundle:Feedback]
          factory_service: doctrine.orm.entity_manager
          factory_method: getRepository
