VM\MakerBundle\Entity\Advert:
    type: entity
    table: adverts
    repositoryClass: VM\MakerBundle\Repository\AdvertRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name: { type: string, length: 255 }
        address: { type: text, nullable: TRUE }
        locality: { type: string, length: 255, nullable: TRUE }
        country: { type: string, length: 255, nullable: TRUE }
        lng: { type: string, length: 30, nullable: TRUE }
        lat: { type: string, length: 30, nullable: TRUE }
        text_introduction: { type: text, nullable: TRUE }
        text_description: { type: text, nullable: TRUE }
        approbation: { type: integer, nullable: TRUE }
        published: { type: integer, nullable: TRUE }
        published_at: { type: datetime, nullable: TRUE }
        start_date: { type: datetime, nullable: TRUE }
        end_date: { type: datetime, nullable: TRUE }
        closed: { type: boolean, nullable: TRUE }
        period: { type: string, length: 255, nullable: TRUE }
        type: { type: string, length: 255, nullable: TRUE }
        advert_type: { type: integer, nullable: TRUE }
        wage_cost: { type: string, length: 255, nullable: TRUE }
        tags: { type: array,  }
        created_at:
          type: date
          nullable: TRUE
          gedmo:
            timestampable:
              on: create
        updated_at:
          type: datetime
          nullable: TRUE
          gedmo:
            timestampable:
              on: update
        slug:
          type: string
          length: 255
          unique: TRUE
          gedmo:
            slug:
              separator: -
              fields:
                - name
    manyToOne:
      Maker:
        targetEntity: VM\MakerBundle\Entity\Maker
        inversedBy: Advert
        joinColumns:
          maker_id:
            referencedColumnName: id
    oneToMany:
        AdvertQuestionnaire:
            targetEntity: VM\MakerBundle\Entity\AdvertQuestionnaire
            mappedBy: Advert
            cascade: [persist]
    lifecycleCallbacks: {  }
