VM\MakerBundle\Entity\MakerInvitationAdministrator:
    type: entity
    table: makers_invitations_administrators
    repositoryClass: VM\MakerBundle\Repository\MakerInvitationAdministratorRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        email: { type: string, length: 255 }
        roles: { type: array }
        confirmation_token : { type: string, lenght: 255, nullable: TRUE }
        created_at:
          type: datetime
          nullable: TRUE
          gedmo:
            timestampable:
              on: create
        updated_at:
          type: datetime
          nullable: TRUE
          gedmo:
            timestampable:
              on: update
    manyToOne:
      Maker:
        targetEntity: VM\MakerBundle\Entity\Maker
        inversedBy: MakerInvitationAdministrator
        joinColumns:
          maker_id:
            referencedColumnName: id
      User:
        targetEntity: VM\UserBundle\Entity\User
        inversedBy: MakerInvitationAdministrator
        joinColumns:
          user_id:
            referencedColumnName: id
    lifecycleCallbacks: {  }
