VM\MakerBundle\Entity\MakerAdministrator:
    type: entity
    table: makers_administrators
    repositoryClass: VM\MakerBundle\Repository\MakerAdministratorRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        roles: { type: array }

    manyToOne:
      Maker:
        targetEntity: VM\MakerBundle\Entity\Maker
        inversedBy: MakerAdministrator
        joinColumns:
          maker_id:
            referencedColumnName: id
      User:
        targetEntity: VM\UserBundle\Entity\User
        inversedBy: MakerAdministrator
        joinColumns:
          user_id:
            referencedColumnName: id
    lifecycleCallbacks: {  }
