<?php

namespace SO\UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * OpenIdIdentityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpenIdIdentityRepository extends EntityRepository
{
}
