security:
    encoders:
        Poker\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_MANAGER, ROLE_MODERATOR, ROLE_SALER, ROLE_SALES_MANAGER]
        ROLE_MANAGER: ROLE_USER
        ROLE_MODERATOR:   ROLE_USER
        ROLE_SALER:   ROLE_USER
        ROLE_SALES_MANAGER:   ROLE_USER
        ROLE_SUPER_ADMIN:  [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
                
    providers:
        my_facebook_provider:
          id: my.facebook.user  
        fos_userbundle:
          id: fos_user.user_provider.username_email
        openid_user_manager:
          id: poker.user.openid_user_manager 
            
    firewalls:
        admin:
            pattern: ^/admin
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /admin/login_check
                default_target_path: /admin
            context: my_context
 
        backend:
            pattern: ^/backend
            provider: fos_userbundle
            form_login:
                check_path: /backend/login_check
                login_path: /login_backend
                default_target_path: /backend
            context: my_context
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
            context: my_context
 
            fos_facebook:
                app_url: http://apps.facebook.com/Forma-search/
                server_url: http://localhost/app_dev.php
                check_path: /login_facebook_check   # Pour éviter toute confusion avec le formulaire de base, j'ai spécifié une route pour Facebook
                provider: my_facebook_provider
                
            fp_openid:
                create_user_if_not_exists: true # so createUserFromIdentity method will be called
                provider: openid_user_manager # cf below
                required_attributes:
                    - contact/email
                    - namePerson/first
                    - namePerson/last
 
            anonymous: true
            logout:
                path: /logout
            
    access_control:
        #- { path: ^/demo/secured/hello/admin/, roles: ROLE_ADMIN }
        - { path: ^/admin, roles: ROLE_USER }
        - { path: ^/backend, roles: ROLE_ADMIN }
