Poker\PokerTableBundle\Entity\PokerTable:
    type:  entity
    table: poker_tables
    repositoryClass: Poker\PokerTableBundle\Repository\PokerTableRepository
    fields:
        id:
            type: integer
            generator:
                strategy: AUTO
            id: true
        name:
            type: string
            nullable: true
            length: 255
        round: { type: integer, nullable: TRUE }
        big_blind: { type: integer, nullable: TRUE }
        small_blind: { type: integer, nullable: TRUE }
        elapse_time: { type: integer, nullable: TRUE }
        cards: { type: array, nullable: TRUE }
        cardsUsed: { type: array, nullable: TRUE }
    oneToMany:
      PokerUser:
        targetEntity: Poker\PokerTableBundle\Entity\PokerUser
        mappedBy: PokerTable

    lifecycleCallbacks: {  }