parameters:
#    recrut_online_standard.example.class: VM\StandardBundle\Example

services:
    std_questionnaire_type_element_repository:
        class: VM\StandardBundle\Repository\StdQuestionnaireTypeElementRepository
        arguments: [VMStandardBundle:StdQuestionnaireTypeElement]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    std_question_type_repository:
        class: VM\StandardBundle\Repository\StdQuestionTypeRepository
        arguments: [VMStandardBundle:StdQuestionType]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    std_category_repository:
        class: VM\StandardBundle\Repository\StdCategoryRepository
        arguments: [VMStandardBundle:StdCategory]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    std_question_type_repository:
        class: VM\StandardBundle\Repository\StdQuestionTypeRepository
        arguments: [VMStandardBundle:StdQuestionType]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    std_questionnaire_type_repository:
        class: VM\StandardBundle\Repository\StdQuestionnaireRepository
        arguments: [VMStandardBundle:StdQuestionnaireType]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
    std_questionnaire_type_element_repository:
        class: VM\StandardBundle\Repository\StdQuestionnaireTypeElementRepository
        arguments: [VMStandardBundle:StdQuestionnaireTypeElement]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
