VM\StandardBundle\Entity\StdQuestionnaireType:
    type: entity
    table: std_questionnaires_types
    repositoryClass: VM\StandardBundle\Repository\StdQuestionnaireRepository
    fields:
         id:
            type: integer
            id: true
            generator:
                strategy: AUTO
         name: { type: string, lenght: 255 }
         slug:
           type: string
           length: 255
           unique: true
           gedmo:
             slug:
               separator: -
               fields:
                 - name
    manyToOne:
      Help:
        targetEntity: VM\QuestionnaireBundle\Entity\Help
        inversedBy: StdQuestionnaireType
        joinColumns:
          help_id:
            referencedColumnName: id
    oneToMany:
      Questionnaire:
        targetEntity: VM\QuestionnaireBundle\Entity\Questionnaire
        mappedBy: StdQuestionnaireType
    lifecycleCallbacks: {  }