parameters:
    so_scrap.controller.class: SO\ScrapBundle\Controller\DefaultController

services:
   so_scrap.controller:
        class: %so_scrap.controller.class%
        arguments: [@service_container]
        calls:
            - [ setContainer, [@service_container] ]