fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fac_file:
    resource: "@FACFileBundle/Controller/"
    type:     annotation

fac_user:
    resource: "@FACUserBundle/Controller/"
    type:     annotation

fac_home:
    resource: "@FACHomeBundle/Controller/"
    type:     annotation

fac_general:
    resource: "@FACGeneralBundle/Controller/"
    type:     annotation

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"