VM\UserBundle\Entity\User:
   constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: username
   properties:
        username:
            - NotBlank: ~
        email:
            - NotBlank: ~
            - Email:
                message: The email "{{ value }}" is not a valid email.
                checkMX: true
                
VM\UserBundle\Entity\UserProfile:
   properties:
        firstname:
            - NotBlank: ~
        lastname:
            - NotBlank: ~
        gender:
            - NotBlank: ~                