parameters:
#    recrut_online_user.example.class: VM\UserBundle\Example
 # we used an EntityManager, so don't forget it in dependency injection
        # you may want to adapt it, only the IdentityManager is mandatory
services:            
    recrut_online.user.openid_user_manager:
        class: VM\UserBundle\Security\OpenIdUserManager
        arguments: ["@fp_openid.identity_manager", "@doctrine.orm.entity_manager", "@fos_user.user_manager"]
    my.facebook.user:
        class: VM\UserBundle\Security\Provider\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@fos_user.user_manager"
            validator: "@validator"
    recrut_online_user.registration.form.type:
        class: VM\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: recrut_online_user_registration }
    recrut_online_user.profile.form.type:
        class: VM\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: recrut_online_user_profile }
    recrut_online_user.change_email.form.type:
        class: VM\UserBundle\Form\Type\ChangeEmailFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: recrut_online_user_change_email }      
    user_repository:
        class: VM\UserBundle\Repository\UserRepository
        arguments: [VMUserBundle:User]
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository       
    auto_login:
        class: VM\UserBundle\Controller\LoginController
        arguments:
            - "@service_container"      