Poker\UserBundle\Entity\UserProfile:
    type:  entity
    table: users_profile
    fields:
          id:
            type: integer
            id: true
            generator:
                strategy: AUTO
          firstname: { type: string, length: 200 }
          lastname: { type: string, length: 200 }
    oneToOne:
      User:
        targetEntity: Poker\UserBundle\Entity\User
        joinColumn:
          name: user_id
          referencedColumnName: id
        cascade: ["persist", "merge"]
        inversedBy: UserProfile