mo_recording_session_creation:
    pattern:  /admin/session_enregistrement/creation
    defaults: { _controller: VMRecordingSessionBundle:Form:recordingSessionCreation }

mo_recording_session_new:
    pattern:  /admin/session_enregistrement/new
    defaults: { _controller: VMRecordingSessionBundle:Form:recordingSessionForm }
    
mo_recording_session_create:
    pattern:  /admin/session_enregistrement/create
    defaults: { _controller: VMRecordingSessionBundle:Form:recordingSessionForm }
    
mo_recording_session_edit:
    pattern:  /admin/session_enregistrement/edit/{slug_sess}
    defaults: { _controller: VMRecordingSessionBundle:Form:recordingSessionForm }   
    
mo_recording_session_update:
    pattern:  /admin/session_enregistrement/update/{slug_sess}
    defaults: { _controller: VMRecordingSessionBundle:Form:recordingSessionForm }

mo_recording_session_user_delete:
    pattern:  /admin/session_enregistrement/{slug_sess}/session_user
    defaults: { _controller: VMRecordingSessionBundle:RecordingSession:moSessionUserDelete }
    
mo_recording_session_show:
    pattern:  /admin/session_enregistrement/{slug_sess}
    defaults: { _controller: VMRecordingSessionBundle:RecordingSession:moShow }

mo_ajax_form_save:
    pattern:  /admin/session_enregistrement/{slug_sess}/ajax/save
    defaults: { _controller: VMRecordingSessionBundle:RecordingSession:moAjaxSaveForm }
    
mo_ajax_word_save:
    pattern:  /admin/session_enregistrement/{slug_sess}/ajax/word/save
    defaults: { _controller: VMRecordingSessionBundle:RecordingSession:moAjaxSaveXord }
  
mo_ajax_word_del:
    pattern:  /admin/session_enregistrement/{slug_sess}/ajax/word/del
    defaults: { _controller: VMRecordingSessionBundle:RecordingSession:moAjaxDelWord }
    
fo_recording_session_show:
    pattern:  /session_enregistrement/{slug_sess}
    defaults: { _controller: VMRecordingSessionBundle:RecordingSession:foShow }

mo_recording_session_dashboard:
    pattern:  /admin/session_enregistrement/{slug_sess}/enregistrements
    defaults: { _controller: VMRecordingSessionBundle:RecordingSession:moSessionDashboard }
    
session_login:
    pattern:  /session_enregistrement/{slug_sess}/login
    defaults: { _controller: VMRecordingSessionBundle:RecordingSession:sessionLogin }